### ISSUE TITLE
undefined method `google_sign_in_button'

### ISSUE THREAD

**Issue by korakotlee** [basecamp/google_sign_in#40]
Do I need to run any rake task to install this to my rails app?
I don't see any route to /google_sign_in/callback to my `routes.rb` file either.

**Comment by wbotelhos** [comment]
Hi @korakotlee ,

You just need put `gem 'google_sign_in'` in you `Gemfile` and execute `bundle install`.
The `undefined` method should be the missing install.

The route `/google_sign_in/callback` will be mounted via Engine, so you will see a route `/callback` inside a namespace `google_sign_in`.

Hope you get it.

**Comment by pisaacs** [comment]
Confirming I had this issue too but found the root cause. 

By default, the Rubygems.org page for this gem will give you the an older gem to use, specifically:
`gem 'google_sign_in', '~> 0.1'`

However, you need to use (or select on the rubygems.org page) the latest version of the gem:
`gem 'google_sign_in', '~> 1.1', '>= 1.1.2'`
